version: '3.8'

services:
  backend:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./kso_frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3001:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge